name: Review dog

on:
  pull_request:
    branches:
      - main

jobs:
  reviewdog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Spellcheck
        uses: reviewdog/action-misspell@v1.27.0
        with:
          reporter: github-pr-review
          locale: US

      - name: Action lint
        uses: reviewdog/action-actionlint@v1.69.1
        with:
          reporter: github-pr-review

      - name: Docker lint
        uses: reviewdog/action-hadolint@v1.50.2
        with:
          reporter: github-pr-review

      - name: YAML lint
        uses: reviewdog/action-yamllint@v1.21.0
        with:
          reporter: github-pr-review

      - name: Markdown lint
        uses: reviewdog/action-markdownlint@v0.26.2
        with:
          reporter: github-pr-review
